name: Generate Datas

on:
  schedule:
    - cron: "1 * * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update Data
    runs-on: ubuntu-latest
    steps:
     uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: MattheusSantana
          svg_out_path: dist/github-contribution-grid-snake.svg


      - name: Deploy Data
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
